stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
    - src/data/data_ingestion.py
    params:
    - data_ingestion.test_size
    outs:
    - data/raw

  data_preprocessing:
    cmd: python src/features/data_preprocessing.py
    deps:
    - data/raw
    - src/features/data_preprocessing.py
    outs:
    - data/interim

  feature_engineering:
    cmd: python src/features/feature_engineering.py
    deps:
    - data/interim
    - src/features/feature_engineering.py
    params:
    - feature_engineering.max_features
    outs:
    - data/features

  model_building:
    cmd: python src/model/model_building.py
    deps:
    - data/features
    - src/model/model_building.py
    outs:
    - models/model.pkl

  model_evaluation:
    cmd: python src/model/model_evaluation.py
    deps:
    - models/model.pkl
    - src/model/model_evaluation.py
    metrics:
    - reports/metrics.json
    outs:
    - 'reports/model_info.json' 

  model_registration:
    cmd: python src/model/register_model.py
    deps:
    - reports/model_info.json
    - src/model/register_model.py