name: CI Pipeline 

on:
  push:
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run DVC ML-Pipeline 
        env:
          DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
        run: |
          dvc repro

      - name: Run test
        env: 
          DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
        run: |
          python -m pytest tests/test_model.py -v

      - name: Promote model to Production
        if: success()
        env:
          DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT}}
        run: |
          python scripts/promote_model.py

      - name: Run Flask app test
        if: success()
        env:
          DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT}}
        run: |
          python -m pytest tests/test_flask_app.py -v 
      
      - name: Login to DockerHub
        if: success()
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build the docker image
        if: success()
        run: |
          docker build -t crownai/mlops-small-project:latest .

      - name: Push the docker image
        if: success()
        run: |
          docker push crownai/mlops-small-project:latest

      - name: Deploy to EC2
        if: success()
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/mlops-small-project:latest
            docker stop sentiment-analysis-app || true
            docker rm sentiment-analysis-app || true
            docker run -d --name sentiment-analysis-app -p 8501:8501 \
              -e DAGSHUB_PAT=${{ secrets.DAGSHUB_PAT }} \
              ${{ secrets.DOCKERHUB_USERNAME }}/mlops-small-project:latest